### ISSUE TITLE
Settings of repo visible where i have no access

### ISSUE THREAD

**Issue by davidak** [woodpecker-ci/woodpecker#321] opened 2021-09-18 06:51 UTC
### Component

web-ui

### Describe the bug

i can see the settings of a repo that i don't have access to

e.g. https://ci.codeberg.org/steko/ci-test/settings

i can change settings there, but get an error

> Failed to update the repository settings

i think i shouldn't see this or at least not be able to change the settings (inactive elements)

secrets and registry load forever, so i'm not able to see them, but it should also be more user friendly. like showing "you don't have access to this information."

when i have opened publicly visible repos while being logged in, they will be listed in my repo list an on the left side. it looks like i can disable them, but also get an error. it is an issue that they clutter my list and i can't remove them https://ci.codeberg.org/account/repos

maybe that will be fixed by https://github.com/woodpecker-ci/woodpecker/pull/245? @anbraten

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"a07f120d"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.github.io/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by anbraten** [comment] 2021-09-18 07:03
Duplicate of #229
Will be fixed by #245

**Closed by anbraten** 2021-09-18 07:03 UTC
