### ISSUE TITLE
Clicking "Details" in Gitea shows UI error box in Woodpecker

### ISSUE THREAD

**Issue by RatherLogical** [woodpecker-ci/woodpecker#689] opened 2022-01-14 18:18 UTC
### Component

web-ui

### Describe the bug

Clicking this "Details" button:
![image](https://user-images.githubusercontent.com/39105734/149564809-816db426-82b9-4bef-aeba-1ddca647c9ec.png)
Shows this error in the bottom right corner:
![image](https://user-images.githubusercontent.com/39105734/149564964-557bed08-b775-4de1-9966-ed37ebbd525b.png)

It is due to the **1** i.e. `https://ci.domain.com/org/repo/build/num/**1**`

It should be **2** on success, or **x** on failure where **x** is the step it failed on.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-dec0eeee"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by anbraten** [comment] 2022-01-15 20:10
seems to be a duplicate of #672

**Closed by anbraten** 2022-01-15 20:10 UTC
Labels: pending:bug
