### ISSUE TITLE
unclear workflow lint

### ISSUE THREAD

**Issue by wez** [woodpecker-ci/woodpecker#3630] opened 2024-04-19 18:50 UTC
### Component

web-ui

### Describe the bug

This set of lints provides no actionable context to understand the issue or how to resolve it; it just says that there is a bad habit.
In addition, because the English language is what it is, the phrasing is extra difficult to parse and understand:

`Please set an event filter on all when branches`

I'd recommend quoting the `"when"` so that the grammar is easy to understand.  Should `"event"` also be quoted? I'm not sure what the linter is looking for.

![image](https://github.com/woodpecker-ci/woodpecker/assets/117777/5d765293-d170-4c2b-8b0d-eb1c82b0ec02)

It's also unclear to me why 6 warnings are generated from the input (see below).

What I think would make things easier for users is:

* It should at least reference the file name and line number like some of the other lints
* Have the lint message suggest what should be added to resolve it. Should there be an `event:` field added? If so, can we make the lint message say that plainly?
* The documentation should be clearer about the recommended syntax and schema for workflow level conditions

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.4.1"}
```

### Additional context

Here's the `when` portion of my workflow:

```yaml
when:
  - event: [push, pull_request, manual]
  - path:
      include:
        - .woodpecker/docs.yml
        - docs/**
        - mkdocs-base.yml
        - stylua.toml
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by anbraten** [comment] 2024-04-19 18:53
duplicate of #3630

**Closed by anbraten** 2024-04-19 18:53 UTC
Labels: bug
