### ISSUE TITLE
Enable one Instance to use multiple forges

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/woodpecker#1376] opened 2022-10-30 16:23 UTC
### Clear and concise description of the problem

When running in smaller environments, running multiple instances (server and agent combo) might be cumbersome / limiting the resources available to an instance and making each instance slow. This is especially pressing, when deploying via container (mostly Kubernetes, Docker does not have Quotas if I remember correctly) with resource quotas set (which is often required to protect services in fairly resource limited setups)

Additionally switching between instances and not confusing them might add another layer of user workload.

### Suggested solution

Enable the use of multiple forges in one woodpecker-server (the agent should be pretty much uninfluenced by this), best case allowing for user mappings, so a single login will manage all forges.

### Alternative

Add a way of at least having multiple authentication sources (effectively forges) and switch between the accounts, while still using the same instance of woodpecker.

### Additional context

I am absolutely unclear whether something like this is feasible, but it would be nice for people having to spread across multiple forges (i.e. Github and their own Gitea instance).

A nice "premium" feature would be if it would be possible to configure multiple forges of the same type in one server instance (which would at least require changing the way the forge-configs are handed over to the instance).

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment] 2022-10-30 16:28
Would be a really nice feature I am looking forward to as well. 

For preparation I've created #1295

duplicate of #138

**Closed by anbraten** 2022-10-30 16:28 UTC
Labels: pending:feature

**Comment by gapodo** [comment] 2022-10-30 16:34
Damn, sorry thought I've searched, but must have done / searched for something wrong... my bad
