### ISSUE TITLE
deleting registry in settings does not remove the registry

### ISSUE THREAD

**Issue by eleith** [woodpecker-ci/woodpecker#520] opened 2021-11-20 18:33 UTC
### Component

server, web-ui

### Describe the bug

reproducible steps

1. add two private registries to a repo
2. remove a registry
3. notice that two registries still remain

expected
1. only one registry is left

### System Info

```shell
next-4891f104
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by eleith** [comment] 2021-11-20 21:59
cli also runs into likely the same error. output is

`error="client error 500: Error deleting registry \"docker.io\". sql: no rows in result set"`

**Comment by 6543** [comment] 2021-11-21 03:37
@eleith could you try latest `next` image?

I can not reproduce your bug

**Comment by 6543** [comment] 2021-11-21 03:50
> cli also runs into likely the same error. output is
> 
> `error="client error 500: Error deleting registry \"docker.io\". sql: no rows in result set"`

you have to specify the hostname to delete one via cli! ...
the error is missleading and I'll created an issue for that: #524

**Comment by eleith** [comment] 2021-11-21 04:29
i can replicate. i have also narrowed down the issue. 

i can delete _some_ registries. but if i enter a registry of this form `https://registry-name.io` then that registry can not be deleted.

registries without a schema can be deleted.

**Comment by 6543** [comment] 2021-11-24 01:13
it's because of your router we use: https://github.com/gin-gonic/gin/pull/2956

**Comment by 6543** [comment] 2021-11-25 17:50
ok found the issue and it's fixed in  #532

**Closed** 2021-11-25 18:04 UTC
Labels: bug

**Comment by 6543** [comment] 2021-11-25 19:32
thanks for running `:next` & reporting bugs, it really help improving woodpecker :rocket:
-> fix is now published in docker-hub @eleith
