### ISSUE TITLE
add option to download raw job output

### ISSUE THREAD

**Issue by MFTabriz** [woodpecker-ci/woodpecker#1016] opened 2022-07-06 19:39 UTC
### Clear and concise description of the problem

Currently each [line number, output line, and timing info] are enclosed in a single <div> and it’s not possible to easily grab (copy-paste) the job output.

Having the possibility of seeing/downloading raw job output (without the line number and the timing) would be really great for debugging and also reporting/archiving.

### Suggested solution

a button to see "raw output" for each job

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment] 2022-07-06 19:48
duplicate of #566

**Closed by anbraten** 2022-07-06 19:48 UTC
Labels: pending:feature
