### ISSUE TITLE
document API

### ISSUE THREAD

**Issue by KiaraGrouwstra** [woodpecker-ci/woodpecker#1101] opened 2022-08-13 19:13 UTC
### Clear and concise description of the problem

it is currently hard to find how to use the REST API in the documentation

### Suggested solution

add documentation with a brief example of how to use the api

### Alternative

reopen #293

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment] 2022-08-13 19:36
duplicate of  #292

**Closed by 6543** 2022-08-13 19:36 UTC
Labels: pending:feature
