### ISSUE TITLE
Disable update notifications and fix icon

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#2760] opened 2023-11-06 09:12 UTC
### Component

web-ui

### Describe the bug

Followup to https://github.com/woodpecker-ci/woodpecker/pull/2722

The Icon is broken in the light mode and there should be an option to disable notifications.

### System Info

```shell
latest
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment] 2023-11-06 09:15
duplicate of #2748 

Why should it be disabled? It's a security feature to push admins towards an up-to-date system.

**Closed by anbraten** 2023-11-06 09:15 UTC
Labels: bug
